sudo: required
services:
  - docker

before_install:
  - docker build -t chintangajjar/react-test -f /client/Dockerfile.dev ./client

scripts:
  - docker run chintangajjar/react-test npm test -- --coverage

after_success:
  - docker build -t chintangajjar/multi-client ./client
  - docker build -t chintangajjar/multi-server ./server
  - docker build -t chintangajjar/multi-worker ./worker
  - docker build -t chintangajjar/multi-nginx ./nginx
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push chintangajjar/multi-client
  - docker push chintangajjar/multi-server
  - docker push chintangajjar/multi-worker
  - docker push chintangajjar/multi-nginx



